APP_NAME = "PZ Mod Manager"
APP_VERSION = "0.1.0"
STEAM_WORKSHOP_PZ_APP_ID = "108600"

COLUMN_ENABLED = 0
COLUMN_MOD_ID = 1
COLUMN_WORKSHOP_ID = 2
COLUMN_NAME = 3
COLUMN_HEADERS = ["Enabled", "Mod ID", "Workshop ID", "Name"]
